// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ8kA5gJrBsSTc3pUQXwCt4hiY-N5lpig',
    appId: '1:187671464883:web:ebd73c0fa29eac93ce19c6',
    messagingSenderId: '187671464883',
    projectId: 'wecan-964f8',
    authDomain: 'wecan-964f8.firebaseapp.com',
    storageBucket: 'wecan-964f8.firebasestorage.app',
    measurementId: 'G-LH4VE6S2HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA08S6U-RY8_-2i60AvSF8IoNlI-nPz168',
    appId: '1:187671464883:android:d7f841e162f9e3f9ce19c6',
    messagingSenderId: '187671464883',
    projectId: 'wecan-964f8',
    storageBucket: 'wecan-964f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKSoG0knxdnlGoJ9FrnU3iBflkiCIlj_U',
    appId: '1:187671464883:ios:420043b748a37da1ce19c6',
    messagingSenderId: '187671464883',
    projectId: 'wecan-964f8',
    storageBucket: 'wecan-964f8.firebasestorage.app',
    iosBundleId: 'com.example.wecanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKSoG0knxdnlGoJ9FrnU3iBflkiCIlj_U',
    appId: '1:187671464883:ios:420043b748a37da1ce19c6',
    messagingSenderId: '187671464883',
    projectId: 'wecan-964f8',
    storageBucket: 'wecan-964f8.firebasestorage.app',
    iosBundleId: 'com.example.wecanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ8kA5gJrBsSTc3pUQXwCt4hiY-N5lpig',
    appId: '1:187671464883:web:30c4b480e7609e1ace19c6',
    messagingSenderId: '187671464883',
    projectId: 'wecan-964f8',
    authDomain: 'wecan-964f8.firebaseapp.com',
    storageBucket: 'wecan-964f8.firebasestorage.app',
    measurementId: 'G-MENQQ9Q9SB',
  );
}
